language: minimal
os:
  - linux
  - windows
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.8.212-04"
    - JDK="adopt-openj9@1.11"
    - MAVEN_VERSION="3.6.3"
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - source $GRAVIS/install-maven
cache:
  directories:
    - $HOME/.jabba/
    - $HOME/.m2
script: mvn clean install
